//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace BlogApplication.Connection.Translation
{
    
    public partial class CategoryTranslationRepository : 
    BlogApplication.Connection.Repository<BlogApplication.Data.Translation.CategoryTranslation>,
    BlogApplication.Entity.Translation.ICategoryTranslationRepository
    {
    	public CategoryTranslationRepository(BlogApplication.Entity.IUnitOfWork unitOfWork) : base(unitOfWork) { }
    }

}
