//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace BlogApplication.Connection.Translation
{
    
    public partial class CommonRepository : 
    BlogApplication.Connection.Repository<BlogApplication.Data.Translation.Common>,
    BlogApplication.Entity.Translation.ICommonRepository
    {
    	public CommonRepository(BlogApplication.Entity.IUnitOfWork unitOfWork) : base(unitOfWork) { }
    }

}
