//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace BlogApplication.Connection.Blog
{
    
    public partial class BlogContentRepository : 
    BlogApplication.Connection.Repository<BlogApplication.Data.Blog.BlogContent>,
    BlogApplication.Entity.Blog.IBlogContentRepository
    {
    	public BlogContentRepository(BlogApplication.Entity.IUnitOfWork unitOfWork) : base(unitOfWork) { }
    }

}
