//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace BlogApplication.Entity.Visa
{
    
    public partial interface IUserRepository : BlogApplication.Entity.IRepository<BlogApplication.Data.Visa.User> { }

}
