//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace BlogApplication.Connection.General
{
    
    public partial class LogRepository : 
    BlogApplication.Connection.Repository<BlogApplication.Data.General.Log>,
    BlogApplication.Entity.General.ILogRepository
    {
    	public LogRepository(BlogApplication.Entity.IUnitOfWork unitOfWork) : base(unitOfWork) { }
    }

}
