//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using BlogApplication.Data.Visa;
using BlogApplication.Data.Blog;
using BlogApplication.Data.Translation;
using BlogApplication.Data.MainSystem;
using BlogApplication.Data.General;

namespace BlogApplication.Data.Visa
{
    [DataContract(IsReference = true)]
    public partial class User
    {
    	[DataMember]
        public long ID { get; set; }
    	[DataMember]
        public string FirstName { get; set; }
    	[DataMember]
        public string LastName { get; set; }
    	[DataMember]
        public string Username { get; set; }
    	[DataMember]
        public string Email { get; set; }
    	[DataMember]
        public string Password { get; set; }
    	[DataMember]
        public string PaswordSalt { get; set; }
    	[DataMember]
        public Nullable<long> MainLanguageID { get; set; }
    	[DataMember]
        public Nullable<byte> StatusID { get; set; }
    	[DataMember]
        public Nullable<byte> UserType { get; set; }
    	[DataMember]
        public string UserProfilePic { get; set; }
    	[DataMember]
        public Nullable<long> DomainID { get; set; }
    }
}
